FROM node:22.7 as build

WORKDIR /app

COPY ./package.json /app/package.json
COPY ./package-lock.json /app/package-lock.json

RUN npm install
COPY . .
RUN npm run build


FROM nginx
COPY --from=build /app/dist /usr/share/nginx/html
