apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: torpedodge-tls
spec:
  secretName: torpedodge-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  dnsNames:
    - torpedodge.resamvi.io
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
