apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik
  namespace: default
spec:
  ingressClassName: traefik
  rules:
  - host: torpedodge.resamvi.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: torpedodge-client
            port:
              number: 8081
  - host: gameserver.resamvi.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: torpedodge-server
            port:
              number: 8080
  tls:
    - secretName: torpedodge-tls
      hosts:
        - torpedodge.resamvi.io
    - secretName: torpedodge-server-tls
      hosts:
        - gameserver.resamvi.io
