apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  namespace: default
  traefik.ingress.kubernetes.io/router.middlewares: default-redirecthttp@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
  - host: torpedodge.resamvi.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: torpedodge-client-path
            port:
              number: 8081
        
  - host: gameserver.resamvi.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gameserver-path
            port:
              number: 8080
  tls:
    - secretName: torpedodge-tls
      hosts:
        - torpedodge.resamvi.io
        - gameserver.resamvi.io
