name: Build/Push Client

on:
  push:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image (client)
        uses: docker/build-push-action@v2
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/torpedodge-client:${{ github.sha }}, ghcr.io/${{ github.repository_owner }}/torpedodge-client:latest
      - name: Build and push Docker image (server)
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/torpedodge-server:${{ github.sha }}, ghcr.io/${{ github.repository_owner }}/torpedodge-server:latest
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
          kubectl config set-context --current --namespace=default
      - name: Deploy to Kubernetes
        run: |
          kubectl rollout restart deployment/torpedodge-client
          kubectl rollout restart deployment/torpedodge-server
