name: Build/Push Client

on:
  push:

env:
  DOCKER_IMAGE_NAME: torpedodge-client
  DOCKERFILE_PATH: ./client/Dockerfile

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./client
          file: ${{ env.DOCKERFILE_PATH }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}, ghcr.io/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE_NAME }}:latest
      - name: Add custom CA certificate
        run: |
          echo "${{ secrets.CERTIFICATE }}" | sudo tee /usr/local/share/ca-certificates/custom-ca.crt
          sudo update-ca-certificates
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'
      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
          kubectl config set-context --current --namespace=default
      - name: Deploy to Kubernetes
        run: |
          kubectl get pods
